package com.dianping.dw.hive.mapper;

import com.dianping.dw.hive.model.QueryLogDO;
import com.dianping.dw.hive.model.QueryLogDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QueryLogDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int countByExample(QueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByExample(QueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insert(QueryLogDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insertSelective(QueryLogDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    List<QueryLogDO> selectByExample(QueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    QueryLogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExampleSelective(@Param("record") QueryLogDO record,
            @Param("example") QueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExample(@Param("record") QueryLogDO record,
            @Param("example") QueryLogDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKeySelective(QueryLogDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_QueryLog
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKey(QueryLogDO record);
}