package com.dianping.dw.hive.mapper;

import com.dianping.dw.hive.model.QueryDO;
import com.dianping.dw.hive.model.QueryDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QueryDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int countByExample(QueryDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByExample(QueryDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insert(QueryDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insertSelective(QueryDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    List<QueryDO> selectByExample(QueryDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    QueryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExampleSelective(@Param("record") QueryDO record,
            @Param("example") QueryDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExample(@Param("record") QueryDO record, @Param("example") QueryDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKeySelective(QueryDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKey(QueryDO record);
}