package com.dianping.dw.hive.mapper;

import com.dianping.dw.hive.model.UserPersonalizationDO;
import com.dianping.dw.hive.model.UserPersonalizationDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPersonalizationDOMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int countByExample(UserPersonalizationDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByExample(UserPersonalizationDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insert(UserPersonalizationDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int insertSelective(UserPersonalizationDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    List<UserPersonalizationDO> selectByExample(UserPersonalizationDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    UserPersonalizationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserPersonalizationDO record,
            @Param("example") UserPersonalizationDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByExample(@Param("record") UserPersonalizationDO record,
            @Param("example") UserPersonalizationDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKeySelective(UserPersonalizationDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_UserPersonalization
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    int updateByPrimaryKey(UserPersonalizationDO record);
}