package com.dianping.dw.hive.model;

import java.util.Date;

import com.dianping.dw.hive.util.CommonUtil;

public class QueryLogDO {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.ID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.AddTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private Date addTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.UpdateTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private Date updateTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.UUID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String uuid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.AdminID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private Integer adminId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.DatabaseName
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String databaseName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.QueryEngine
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String queryEngine;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.Role
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String role;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.Properties
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String properties;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.QuerySql
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String querySql;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.ExecTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private Integer execTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.QueryStatus
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String queryStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.ResultFilePath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String resultFilePath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.LogPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String logPath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.CsvPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String csvPath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.XlsxPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String xlsxPath;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column HW_QueryLog.Detail
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.ID
     * @return  the value of HW_QueryLog.ID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.ID
     * @param id  the value for HW_QueryLog.ID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.AddTime
     * @return  the value of HW_QueryLog.AddTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.AddTime
     * @param addTime  the value for HW_QueryLog.AddTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.UpdateTime
     * @return  the value of HW_QueryLog.UpdateTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.UpdateTime
     * @param updateTime  the value for HW_QueryLog.UpdateTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.UUID
     * @return  the value of HW_QueryLog.UUID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.UUID
     * @param uuid  the value for HW_QueryLog.UUID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.AdminID
     * @return  the value of HW_QueryLog.AdminID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.AdminID
     * @param adminId  the value for HW_QueryLog.AdminID
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.DatabaseName
     * @return  the value of HW_QueryLog.DatabaseName
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.DatabaseName
     * @param databaseName  the value for HW_QueryLog.DatabaseName
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.QueryEngine
     * @return  the value of HW_QueryLog.QueryEngine
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getQueryEngine() {
        return queryEngine;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.QueryEngine
     * @param queryEngine  the value for HW_QueryLog.QueryEngine
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setQueryEngine(String queryEngine) {
        this.queryEngine = queryEngine;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.Role
     * @return  the value of HW_QueryLog.Role
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.Role
     * @param role  the value for HW_QueryLog.Role
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.Properties
     * @return  the value of HW_QueryLog.Properties
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.Properties
     * @param properties  the value for HW_QueryLog.Properties
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setProperties(String properties) {
        this.properties = properties;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.QuerySql
     * @return  the value of HW_QueryLog.QuerySql
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getQuerySql() {
        return querySql;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.QuerySql
     * @param querySql  the value for HW_QueryLog.QuerySql
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setQuerySql(String querySql) {
        this.querySql = querySql;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.ExecTime
     * @return  the value of HW_QueryLog.ExecTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Integer getExecTime() {
        return execTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.ExecTime
     * @param execTime  the value for HW_QueryLog.ExecTime
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setExecTime(Integer execTime) {
        this.execTime = execTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.QueryStatus
     * @return  the value of HW_QueryLog.QueryStatus
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getQueryStatus() {
        return queryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.QueryStatus
     * @param queryStatus  the value for HW_QueryLog.QueryStatus
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setQueryStatus(String queryStatus) {
        this.queryStatus = queryStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.ResultFilePath
     * @return  the value of HW_QueryLog.ResultFilePath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getResultFilePath() {
        return resultFilePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.ResultFilePath
     * @param resultFilePath  the value for HW_QueryLog.ResultFilePath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setResultFilePath(String resultFilePath) {
        this.resultFilePath = resultFilePath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.LogPath
     * @return  the value of HW_QueryLog.LogPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getLogPath() {
        return logPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.LogPath
     * @param logPath  the value for HW_QueryLog.LogPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setLogPath(String logPath) {
        this.logPath = logPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.CsvPath
     * @return  the value of HW_QueryLog.CsvPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getCsvPath() {
        return csvPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.CsvPath
     * @param csvPath  the value for HW_QueryLog.CsvPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setCsvPath(String csvPath) {
        this.csvPath = csvPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.XlsxPath
     * @return  the value of HW_QueryLog.XlsxPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getXlsxPath() {
        return xlsxPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.XlsxPath
     * @param xlsxPath  the value for HW_QueryLog.XlsxPath
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setXlsxPath(String xlsxPath) {
        this.xlsxPath = xlsxPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column HW_QueryLog.Detail
     * @return  the value of HW_QueryLog.Detail
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column HW_QueryLog.Detail
     * @param detail  the value for HW_QueryLog.Detail
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    @Override
    public String toString() {
        return CommonUtil.toJson(this);
    }

}