package com.dianping.dw.hive.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QueryDOExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public QueryDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("AddTime is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("AddTime is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("AddTime =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("AddTime <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("AddTime >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("AddTime >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("AddTime <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("AddTime <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("AddTime in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("AddTime not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("AddTime between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("AddTime not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("UUID is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("UUID is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("UUID =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("UUID <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("UUID >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("UUID >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("UUID <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("UUID <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("UUID like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("UUID not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("UUID in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("UUID not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("UUID between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("UUID not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("AdminID is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("AdminID is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("AdminID =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("AdminID <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("AdminID >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("AdminID >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("AdminID <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("AdminID <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("AdminID in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("AdminID not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("AdminID between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("AdminID not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameIsNull() {
            addCriterion("DatabaseName is null");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameIsNotNull() {
            addCriterion("DatabaseName is not null");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameEqualTo(String value) {
            addCriterion("DatabaseName =", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameNotEqualTo(String value) {
            addCriterion("DatabaseName <>", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameGreaterThan(String value) {
            addCriterion("DatabaseName >", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameGreaterThanOrEqualTo(String value) {
            addCriterion("DatabaseName >=", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameLessThan(String value) {
            addCriterion("DatabaseName <", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameLessThanOrEqualTo(String value) {
            addCriterion("DatabaseName <=", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameLike(String value) {
            addCriterion("DatabaseName like", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameNotLike(String value) {
            addCriterion("DatabaseName not like", value, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameIn(List<String> values) {
            addCriterion("DatabaseName in", values, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameNotIn(List<String> values) {
            addCriterion("DatabaseName not in", values, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameBetween(String value1, String value2) {
            addCriterion("DatabaseName between", value1, value2, "databaseName");
            return (Criteria) this;
        }

        public Criteria andDatabaseNameNotBetween(String value1, String value2) {
            addCriterion("DatabaseName not between", value1, value2, "databaseName");
            return (Criteria) this;
        }

        public Criteria andQueryEngineIsNull() {
            addCriterion("QueryEngine is null");
            return (Criteria) this;
        }

        public Criteria andQueryEngineIsNotNull() {
            addCriterion("QueryEngine is not null");
            return (Criteria) this;
        }

        public Criteria andQueryEngineEqualTo(String value) {
            addCriterion("QueryEngine =", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineNotEqualTo(String value) {
            addCriterion("QueryEngine <>", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineGreaterThan(String value) {
            addCriterion("QueryEngine >", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineGreaterThanOrEqualTo(String value) {
            addCriterion("QueryEngine >=", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineLessThan(String value) {
            addCriterion("QueryEngine <", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineLessThanOrEqualTo(String value) {
            addCriterion("QueryEngine <=", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineLike(String value) {
            addCriterion("QueryEngine like", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineNotLike(String value) {
            addCriterion("QueryEngine not like", value, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineIn(List<String> values) {
            addCriterion("QueryEngine in", values, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineNotIn(List<String> values) {
            addCriterion("QueryEngine not in", values, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineBetween(String value1, String value2) {
            addCriterion("QueryEngine between", value1, value2, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andQueryEngineNotBetween(String value1, String value2) {
            addCriterion("QueryEngine not between", value1, value2, "queryEngine");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("Role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("Role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("Role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("Role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("Role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("Role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("Role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("Role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("Role like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("Role not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("Role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("Role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("Role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("Role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNull() {
            addCriterion("Properties is null");
            return (Criteria) this;
        }

        public Criteria andPropertiesIsNotNull() {
            addCriterion("Properties is not null");
            return (Criteria) this;
        }

        public Criteria andPropertiesEqualTo(String value) {
            addCriterion("Properties =", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotEqualTo(String value) {
            addCriterion("Properties <>", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThan(String value) {
            addCriterion("Properties >", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("Properties >=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThan(String value) {
            addCriterion("Properties <", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLessThanOrEqualTo(String value) {
            addCriterion("Properties <=", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesLike(String value) {
            addCriterion("Properties like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotLike(String value) {
            addCriterion("Properties not like", value, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesIn(List<String> values) {
            addCriterion("Properties in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotIn(List<String> values) {
            addCriterion("Properties not in", values, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesBetween(String value1, String value2) {
            addCriterion("Properties between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andPropertiesNotBetween(String value1, String value2) {
            addCriterion("Properties not between", value1, value2, "properties");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIsNull() {
            addCriterion("QuerySql is null");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIsNotNull() {
            addCriterion("QuerySql is not null");
            return (Criteria) this;
        }

        public Criteria andQuerySqlEqualTo(String value) {
            addCriterion("QuerySql =", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotEqualTo(String value) {
            addCriterion("QuerySql <>", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlGreaterThan(String value) {
            addCriterion("QuerySql >", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlGreaterThanOrEqualTo(String value) {
            addCriterion("QuerySql >=", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLessThan(String value) {
            addCriterion("QuerySql <", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLessThanOrEqualTo(String value) {
            addCriterion("QuerySql <=", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlLike(String value) {
            addCriterion("QuerySql like", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotLike(String value) {
            addCriterion("QuerySql not like", value, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlIn(List<String> values) {
            addCriterion("QuerySql in", values, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotIn(List<String> values) {
            addCriterion("QuerySql not in", values, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlBetween(String value1, String value2) {
            addCriterion("QuerySql between", value1, value2, "querySql");
            return (Criteria) this;
        }

        public Criteria andQuerySqlNotBetween(String value1, String value2) {
            addCriterion("QuerySql not between", value1, value2, "querySql");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNull() {
            addCriterion("ExecTime is null");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNotNull() {
            addCriterion("ExecTime is not null");
            return (Criteria) this;
        }

        public Criteria andExecTimeEqualTo(Integer value) {
            addCriterion("ExecTime =", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotEqualTo(Integer value) {
            addCriterion("ExecTime <>", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThan(Integer value) {
            addCriterion("ExecTime >", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ExecTime >=", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThan(Integer value) {
            addCriterion("ExecTime <", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThanOrEqualTo(Integer value) {
            addCriterion("ExecTime <=", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeIn(List<Integer> values) {
            addCriterion("ExecTime in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotIn(List<Integer> values) {
            addCriterion("ExecTime not in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeBetween(Integer value1, Integer value2) {
            addCriterion("ExecTime between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("ExecTime not between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNull() {
            addCriterion("QueryStatus is null");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNotNull() {
            addCriterion("QueryStatus is not null");
            return (Criteria) this;
        }

        public Criteria andQueryStatusEqualTo(String value) {
            addCriterion("QueryStatus =", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotEqualTo(String value) {
            addCriterion("QueryStatus <>", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusGreaterThan(String value) {
            addCriterion("QueryStatus >", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusGreaterThanOrEqualTo(String value) {
            addCriterion("QueryStatus >=", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusLessThan(String value) {
            addCriterion("QueryStatus <", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusLessThanOrEqualTo(String value) {
            addCriterion("QueryStatus <=", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusLike(String value) {
            addCriterion("QueryStatus like", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotLike(String value) {
            addCriterion("QueryStatus not like", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIn(List<String> values) {
            addCriterion("QueryStatus in", values, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotIn(List<String> values) {
            addCriterion("QueryStatus not in", values, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusBetween(String value1, String value2) {
            addCriterion("QueryStatus between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotBetween(String value1, String value2) {
            addCriterion("QueryStatus not between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andResultFilePathIsNull() {
            addCriterion("ResultFilePath is null");
            return (Criteria) this;
        }

        public Criteria andResultFilePathIsNotNull() {
            addCriterion("ResultFilePath is not null");
            return (Criteria) this;
        }

        public Criteria andResultFilePathEqualTo(String value) {
            addCriterion("ResultFilePath =", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathNotEqualTo(String value) {
            addCriterion("ResultFilePath <>", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathGreaterThan(String value) {
            addCriterion("ResultFilePath >", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("ResultFilePath >=", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathLessThan(String value) {
            addCriterion("ResultFilePath <", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathLessThanOrEqualTo(String value) {
            addCriterion("ResultFilePath <=", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathLike(String value) {
            addCriterion("ResultFilePath like", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathNotLike(String value) {
            addCriterion("ResultFilePath not like", value, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathIn(List<String> values) {
            addCriterion("ResultFilePath in", values, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathNotIn(List<String> values) {
            addCriterion("ResultFilePath not in", values, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathBetween(String value1, String value2) {
            addCriterion("ResultFilePath between", value1, value2, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andResultFilePathNotBetween(String value1, String value2) {
            addCriterion("ResultFilePath not between", value1, value2, "resultFilePath");
            return (Criteria) this;
        }

        public Criteria andLogPathIsNull() {
            addCriterion("LogPath is null");
            return (Criteria) this;
        }

        public Criteria andLogPathIsNotNull() {
            addCriterion("LogPath is not null");
            return (Criteria) this;
        }

        public Criteria andLogPathEqualTo(String value) {
            addCriterion("LogPath =", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathNotEqualTo(String value) {
            addCriterion("LogPath <>", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathGreaterThan(String value) {
            addCriterion("LogPath >", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathGreaterThanOrEqualTo(String value) {
            addCriterion("LogPath >=", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathLessThan(String value) {
            addCriterion("LogPath <", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathLessThanOrEqualTo(String value) {
            addCriterion("LogPath <=", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathLike(String value) {
            addCriterion("LogPath like", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathNotLike(String value) {
            addCriterion("LogPath not like", value, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathIn(List<String> values) {
            addCriterion("LogPath in", values, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathNotIn(List<String> values) {
            addCriterion("LogPath not in", values, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathBetween(String value1, String value2) {
            addCriterion("LogPath between", value1, value2, "logPath");
            return (Criteria) this;
        }

        public Criteria andLogPathNotBetween(String value1, String value2) {
            addCriterion("LogPath not between", value1, value2, "logPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathIsNull() {
            addCriterion("CsvPath is null");
            return (Criteria) this;
        }

        public Criteria andCsvPathIsNotNull() {
            addCriterion("CsvPath is not null");
            return (Criteria) this;
        }

        public Criteria andCsvPathEqualTo(String value) {
            addCriterion("CsvPath =", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathNotEqualTo(String value) {
            addCriterion("CsvPath <>", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathGreaterThan(String value) {
            addCriterion("CsvPath >", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathGreaterThanOrEqualTo(String value) {
            addCriterion("CsvPath >=", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathLessThan(String value) {
            addCriterion("CsvPath <", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathLessThanOrEqualTo(String value) {
            addCriterion("CsvPath <=", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathLike(String value) {
            addCriterion("CsvPath like", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathNotLike(String value) {
            addCriterion("CsvPath not like", value, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathIn(List<String> values) {
            addCriterion("CsvPath in", values, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathNotIn(List<String> values) {
            addCriterion("CsvPath not in", values, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathBetween(String value1, String value2) {
            addCriterion("CsvPath between", value1, value2, "csvPath");
            return (Criteria) this;
        }

        public Criteria andCsvPathNotBetween(String value1, String value2) {
            addCriterion("CsvPath not between", value1, value2, "csvPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathIsNull() {
            addCriterion("XlsxPath is null");
            return (Criteria) this;
        }

        public Criteria andXlsxPathIsNotNull() {
            addCriterion("XlsxPath is not null");
            return (Criteria) this;
        }

        public Criteria andXlsxPathEqualTo(String value) {
            addCriterion("XlsxPath =", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathNotEqualTo(String value) {
            addCriterion("XlsxPath <>", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathGreaterThan(String value) {
            addCriterion("XlsxPath >", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathGreaterThanOrEqualTo(String value) {
            addCriterion("XlsxPath >=", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathLessThan(String value) {
            addCriterion("XlsxPath <", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathLessThanOrEqualTo(String value) {
            addCriterion("XlsxPath <=", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathLike(String value) {
            addCriterion("XlsxPath like", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathNotLike(String value) {
            addCriterion("XlsxPath not like", value, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathIn(List<String> values) {
            addCriterion("XlsxPath in", values, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathNotIn(List<String> values) {
            addCriterion("XlsxPath not in", values, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathBetween(String value1, String value2) {
            addCriterion("XlsxPath between", value1, value2, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andXlsxPathNotBetween(String value1, String value2) {
            addCriterion("XlsxPath not between", value1, value2, "xlsxPath");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("Detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("Detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("Detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("Detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("Detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("Detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("Detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("Detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("Detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("Detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("Detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("Detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("Detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("Detail not between", value1, value2, "detail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table HW_Query
     * @mbggenerated  Tue Dec 16 13:40:37 CST 2014
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HW_Query
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 28 10:32:59 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}